FROM node:20-bullseye-slim
WORKDIR /app
ENV NODE_ENV=production PORT=3000 NEXT_TELEMETRY_DISABLED=1

RUN adduser --disabled-password --gecos "" nextjs && chown -R nextjs:nextjs /app
USER nextjs

COPY .next/standalone ./
COPY .next/static ./.next/static
COPY public ./public

EXPOSE 3000
CMD ["node", "server.js"]