services:
  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8000/health"]
      interval: 10s
      timeout: 3s
      retries: 5

  web:
    build:
      context: ./frontend
      # BUILD-TIME vars for Next.js (so they are embedded into the client bundle)
      args:
        NEXT_PUBLIC_ELEVENLABS_AGENT_ID: ${NEXT_PUBLIC_ELEVENLABS_AGENT_ID}
        NEXT_PUBLIC_BACKEND_URL: ${NEXT_PUBLIC_BACKEND_URL}
    environment:
      - NODE_ENV=production
      - PORT=3000
    ports:
      - "3000:3000"
    # depends_on:
    #   backend:
    #     condition: service_healthy
